# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '10.0'
#use_frameworks!
#
#target 'Whack a jellyfish' do
#pod 'Each', '~>1.2'
#  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#
#
#  # Pods for Whack a jellyfish
#
#end

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Whack a jellyfish' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Whack a jellyfish
    
    pod 'Each', '~> 1.2'
    
end
